kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume
  namespace: govinda
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: pv-govinda
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logs"