apiVersion: v1
kind: Pod
metadata:
  labels:
    app: category
  name: category
  namespace: govinda
spec:
  volumes:
  - name: log-volume
    persistentVolumeClaim:
        claimName: log-persistent-claim
  containers:
  - image: apgovinda/category:distributed
    imagePullPolicy: Always
    name: category
    volumeMounts:
    - name: log-volume
      mountPath: "/var/tmp/"
    ports:
    - containerPort: 8082
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
