kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume
  namespace: govinda
  labels:
    type: local
spec:
  storageClassName: mysql-govinda
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
