apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: govinda
spec:
  storageClassName: mysql-govinda
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
